version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:9000"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:V3uB8wXTA+YtUKSIM9sQ2qw9vnAkKu1UaNBgwQYH1ho=
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=SimcoGroup
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            - db
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=SimcoGroup
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_ROOT_PASSWORD=root
